### ISSUE TITLE
Request hangs on CLI

### ISSUE THREAD

**Issue by RichardLitt** [kevva/github-repositories#13]
I am unable to get a response on 3.0.0.

```
$ github-repositories RichardLitt
# nothing for a long time
```

Any thoughts on why this might be?

**Comment by RichardLitt** [comment]
Part of this bug: https://github.com/sindresorhus/gh-got/issues/26. Had to unset `GITHUB_ENDPOINT`. 

Perhaps we should keep this open until that is fixed.

**Comment by kevva** [comment]
Does it error out after a while? I just tried with your username and it worked fine for me: 

```
❯ github-repositories RichardLitt
--- (fork) https://github.com/RichardLitt/---
101 (fork) https://github.com/RichardLitt/101
2014.jsconf.eu (fork) https://github.com/RichardLitt/2014.jsconf.eu
58-liters https://github.com/RichardLitt/58-liters
```

**Comment by kevva** [comment]
> Part of this bug: sindresorhus/gh-got#26. Had to unset `GITHUB_ENDPOINT`.

Oh right. Let's continue the discussion over there.

**Comment by RichardLitt** [comment]
@kevva Figured it out while you were debugging! Thanks for being so quick. See above comment.

**Comment by kevva** [comment]
Closing as this was closed in the issue referenced above.
