### ISSUE TITLE
Promisify

### ISSUE THREAD

**Issue by kevva** [kevva/github-repositories#7]
@SamVerschueren, any suggestions on how to promisify [this](https://github.com/kevva/github-repositories/blob/master/index.js#L8-L26) the best way? I've searched some for recursive promises but couldn't find anything that didn't involve a lot of wrapping/nesting.

**Comment by SamVerschueren** [comment]
My best bet is something like this.

``` js
function getRepos(user, opts) {
    var page = 1;
    var ret = [];

    var url = 'users/' + user + '/repos?&per_page=100&page=' + page;

    return (function loop() {
        return ghGot(url, opts).then(function (res) {
            ret = ret.concat(res.data);

            if (res.headers.link && res.headers.link.indexOf('next') !== -1) {
                return loop();
            }

            return ret;
        });
    }());
}
```

Not sure about `res.data`. Not that familiar with `got`. Will try it out tomorrow if I have more time.

**Comment by sindresorhus** [comment]
@SamVerschueren Yes, that's exactly what I was thinking too.

**Comment by kevva** [comment]
Yeah, must have done something wrong when I tried it earlier :(. Thanks anyway!
